# Generated by Django 5.2.4 on 2025-07-25 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score2Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('SCORE2', 'SCORE2'), ('SCORE2-Diabetes', 'SCORE2-Diabetes'), ('SCORE2-OP', 'SCORE2-OP')], max_length=20)),
                ('score_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(choices=[('low_to_moderate', 'Niskie do umiarkowanego'), ('high', 'Wysokie'), ('very_high', 'Bardzo wysokie'), ('not_applicable', 'Nie dotyczy'), ('age_out_of_range', 'Wiek poza zakresem')], max_length=20)),
                ('region', models.CharField(choices=[('low', 'Niskie ryzyko'), ('moderate', 'Umiarkowane ryzyko'), ('high', 'Wysokie ryzyko'), ('very_high', 'Bardzo wysokie ryzyko')], default='high', max_length=10)),
                ('age_at_calculation', models.IntegerField()),
                ('systolic_pressure', models.IntegerField(blank=True, null=True)),
                ('cholesterol_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cholesterol_hdl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('smoking_status', models.CharField(blank=True, max_length=50, null=True)),
                ('smoking_info_source', models.CharField(blank=True, max_length=100, null=True)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('age_at_diabetes_diagnosis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hba1c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('egfr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cholesterol_info', models.TextField(blank=True, null=True)),
                ('calculation_notes', models.TextField(blank=True, null=True)),
                ('is_calculation_successful', models.BooleanField(default=False)),
                ('missing_data_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score2_results', to='patients.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score2_results', to='patients.visit')),
            ],
            options={
                'db_table': 'score2_results',
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'visit', 'created_at')},
            },
        ),
    ]
