# Generated by Django 5.2.4 on 2025-07-25 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diagnoses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='PESEL musi zawierać 11 cyfr', regex='^\\d{11}$')])),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Mężczyzna'), ('F', 'Kobieta')], max_length=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_landline', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['full_name', 'pesel'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('quarter', models.CharField(blank=True, max_length=10, null=True)),
                ('systolic_pressure', models.IntegerField(blank=True, null=True)),
                ('hba1c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('egfr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cholesterol_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cholesterol_hdl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'db_table': 'visits',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(max_length=10)),
                ('diagnosed_at', models.DateField(blank=True, null=True)),
                ('last_visit_with_condition', models.DateField(blank=True, null=True)),
                ('age_at_diagnosis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_diagnoses', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_diagnoses',
                'ordering': ['diagnosed_at'],
                'unique_together': {('patient', 'diagnosis_code')},
            },
        ),
        migrations.CreateModel(
            name='VisitDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.visit')),
            ],
            options={
                'db_table': 'visit_diagnoses',
                'unique_together': {('visit', 'diagnosis_code')},
            },
        ),
    ]
