# Generated by Django 5.2.4 on 2025-07-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='smoking_status',
            field=models.CharField(choices=[('non_smoker', 'Nie pali'), ('smoker', 'Pali'), ('assumed_non_smoker', 'Zakładany niepali (brak danych)')], default='assumed_non_smoker', max_length=20),
        ),
    ]
